### ISSUE TITLE
Remove="**\*.proto" does not seem to work

### ISSUE THREAD

**Issue by mpdn** [warrenfalk/msbuild-protocol-buffers#2]
Given an empty .proto file and a .csproj like this:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MsBuild.ProtocolBuffers" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProtoC Remove="**\*.proto" />
  </ItemGroup>
</Project>
```

I would expect it to *not* compile the empty .proto file, but it does.

Am I doing anything wrong or is it some kind of bug? I am using VS 2017.

**Comment by mpdn** [comment]
It might be something about the order things are evaluated in MSBuild. I sort of circumvented the problem by introducing a target that runs before `ProtoCalcOutput`:
```
<Target Name="RemoveDefaultProtoTargets" BeforeTargets="ProtoCalcOutput">
  <ItemGroup>
    <ProtoC Remove="@(ProtoC)" />
  </ItemGroup>
</Target>
```
Then I can remove and include items in there instead.

**Comment by warrenfalk** [comment]
@Noctune has the correct solution.  MsBuild is weird.  I've updated the README
